# Generated by Django 5.2.6 on 2025-09-25 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Integración (Inicio), Alcance (Planeación)', max_length=100, unique=True)),
                ('tailwind_bg_color', models.CharField(default='bg-gray-200', help_text='Clase de Tailwind para el fondo del footer. Ej: bg-gray-200', max_length=50)),
                ('tailwind_text_color', models.CharField(default='text-gray-600', help_text='Clase de Tailwind para el texto del footer. Ej: text-gray-800', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Base Estratégica, Ritmo Diario, etc.', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('tailwind_bg_color', models.CharField(default='bg-gray-500', help_text='Clase de Tailwind para el color de fondo. Ej: bg-indigo-800', max_length=50)),
                ('tailwind_text_color', models.CharField(default='text-white', help_text='Clase de Tailwind para el color del texto. Ej: text-white', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PMBOKProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('inputs', models.TextField(blank=True, help_text='Lista de entradas, separadas por saltos de línea.')),
                ('tools_and_techniques', models.TextField(blank=True, help_text='Lista de herramientas y técnicas, separadas por saltos de línea.')),
                ('outputs', models.TextField(blank=True, help_text='Lista de salidas, separadas por saltos de línea.')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processes', to='api.processstage')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processes', to='api.processstatus')),
            ],
            options={
                'ordering': ['process_number'],
            },
        ),
    ]
