# Generated by Django 5.2.6 on 2025-09-25 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Base Estratégica, Ritmo Diario, etc.', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('tailwind_bg_color', models.CharField(default='bg-gray-500', help_text='Clase de Tailwind para el color de fondo. Ej: bg-indigo-800', max_length=50)),
                ('tailwind_text_color', models.CharField(default='text-white', help_text='Clase de Tailwind para el color del texto. Ej: text-white', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PMBOKProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processes', to='api.processstate')),
            ],
            options={
                'ordering': ['process_number'],
            },
        ),
    ]
