# Generated by Django 5.2.6 on 2025-10-11 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pmbokprocesscustomization',
            unique_together={('process', 'country_code', 'department')},
        ),
        migrations.AlterUniqueTogether(
            name='scrumprocesscustomization',
            unique_together={('process', 'country_code', 'department')},
        ),
    ]
