# Generated by Django 5.2.6 on 2025-09-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmbokprocess',
            name='kanban_status',
            field=models.CharField(choices=[('backlog', 'Pendiente'), ('todo', 'Por Hacer'), ('in_progress', 'En Progreso'), ('in_review', 'En Revisión'), ('done', 'Hecho')], default='backlog', help_text='El estado del proceso en el tablero Kanban.', max_length=20),
        ),
    ]
