# Generated by Django 5.2.6 on 2025-09-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_processstate_pmbokprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmbokprocess',
            name='inputs',
            field=models.TextField(blank=True, help_text='Lista de entradas, separadas por saltos de línea.'),
        ),
        migrations.AddField(
            model_name='pmbokprocess',
            name='outputs',
            field=models.TextField(blank=True, help_text='Lista de salidas, separadas por saltos de línea.'),
        ),
        migrations.AddField(
            model_name='pmbokprocess',
            name='tools_and_techniques',
            field=models.TextField(blank=True, help_text='Lista de herramientas y técnicas, separadas por saltos de línea.'),
        ),
    ]
