# Generated by Django 5.2.6 on 2025-09-27 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_pmbokprocess_kanban_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrumProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('inputs', models.TextField(blank=True, help_text='Lista de entradas, separadas por saltos de línea.')),
                ('tools_and_techniques', models.TextField(blank=True, help_text='Lista de herramientas y técnicas, separadas por saltos de línea.')),
                ('outputs', models.TextField(blank=True, help_text='Lista de salidas, separadas por saltos de línea.')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrum_processes', to='api.processstage')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrum_processes', to='api.processstatus')),
            ],
            options={
                'verbose_name': 'Scrum Process',
                'verbose_name_plural': 'Scrum Processes',
                'ordering': ['process_number'],
            },
        ),
    ]
