# Generated by Django 5.2.6 on 2025-09-28 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_scrumprocess'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrumPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Inicio, Planificación y Estimación', max_length=100, unique=True)),
                ('tailwind_bg_color', models.CharField(default='bg-gray-200', help_text='Clase de Tailwind para el fondo del footer. Ej: bg-sky-100', max_length=50)),
                ('tailwind_text_color', models.CharField(default='text-gray-600', help_text='Clase de Tailwind para el texto del footer. Ej: text-sky-800', max_length=50)),
            ],
            options={
                'verbose_name': 'Scrum Phase',
                'verbose_name_plural': 'Scrum Phases',
            },
        ),
        migrations.RemoveField(
            model_name='scrumprocess',
            name='stage',
        ),
        migrations.AlterField(
            model_name='pmbokprocess',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pmbok_processes', to='api.processstage'),
        ),
        migrations.AlterField(
            model_name='pmbokprocess',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pmbok_processes', to='api.processstatus'),
        ),
        migrations.AlterField(
            model_name='scrumprocess',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrum_processes_by_status', to='api.processstatus'),
        ),
        migrations.AddField(
            model_name='scrumprocess',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrum_processes_by_phase', to='api.scrumphase'),
        ),
    ]
