# Generated by Django 5.2.6 on 2025-09-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_scrumphase_remove_scrumprocess_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumprocess',
            name='kanban_status',
            field=models.CharField(choices=[('unassigned', 'No Asignado'), ('backlog', 'Pendiente'), ('todo', 'Por Hacer'), ('in_progress', 'En Progreso'), ('in_review', 'En Revisión'), ('done', 'Hecho')], default='unassigned', help_text='El estado del proceso en el tablero Kanban.', max_length=20),
        ),
        migrations.AlterField(
            model_name='pmbokprocess',
            name='kanban_status',
            field=models.CharField(choices=[('unassigned', 'No Asignado'), ('backlog', 'Pendiente'), ('todo', 'Por Hacer'), ('in_progress', 'En Progreso'), ('in_review', 'En Revisión'), ('done', 'Hecho')], default='unassigned', help_text='El estado del proceso en el tablero Kanban.', max_length=20),
        ),
    ]
