"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
import urllib.request  # <-- Se añade esta librería para la solución del Health Check

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# --- DEBUG leído desde variables de entorno ---
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') != 'False'
IS_PROD = not DEBUG

# --- SECRET_KEY leída desde variables de entorno ---
SECRET_KEY = os.environ.get('SECRET_KEY', None) or (
    'django-insecure-nwpq!$u+9%el8cr9qhkl(=1svcl4=fc@rn)26p(@)g(6xq2$(+'
    if not IS_PROD else (_ for _ in ()).throw(RuntimeError("SECRET_KEY no definido en producción"))
)
# --- ALLOWED_HOSTS ---
# Se mantiene tu lista original para compatibilidad local y de producción.
ALLOWED_HOSTS = [
    'pmbok-app-prod.eba-p9tjqp8p.us-east-1.elasticbeanstalk.com',
    'localhost',
    '127.0.0.1',
    'backend',
    '0.0.0.0',
    '.elasticbeanstalk.com',
    "52.44.102.215",                 # si quieres que la IP responda sin 400
    "elrincondeldetective.com",      # tu dominio si lo apuntas a EB/ALB
    "www.elrincondeldetective.com",
]

# --- Seguridad detrás de ELB/Proxy ---
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
if IS_PROD:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = "Lax"   # ← añade esta línea
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_SAMESITE = "Lax"
    SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = "same-origin"

CSRF_TRUSTED_ORIGINS = [
    "http://elrincondeldetective.com",
    "http://www.elrincondeldetective.com",
    "http://pmbok-app-prod.eba-p9tjqp8p.us-east-1.elasticbeanstalk.com",
    "https://pmbok-app-prod.eba-p9tjqp8p.us-east-1.elasticbeanstalk.com",
    "https://elrincondeldetective.com",
    "https://www.elrincondeldetective.com",
]


# --- SOLUCIÓN PARA EL HEALTH CHECK DE AWS ELASTIC BEANSTALK ---
# Obtiene la IP privada de la instancia EC2 desde el servicio de metadatos de AWS.
# Esto es crucial para que el Health Checker de Elastic Beanstalk pueda acceder a la aplicación.
# Este bloque no afectará tu entorno de desarrollo local.
try:
    EC2_PRIVATE_IP = urllib.request.urlopen(
        'http://169.254.169.254/latest/meta-data/local-ipv4', timeout=1).read().decode()
    if EC2_PRIVATE_IP and EC2_PRIVATE_IP not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(EC2_PRIVATE_IP)
except Exception as e:
    # No hacer nada si no se puede obtener la IP (por ejemplo, en desarrollo local)
    pass
# --- FIN DE LA SOLUCIÓN ---


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Django 5: backend de estáticos (equivale al antiguo STATICFILES_STORAGE)
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    }
}

# --- Orígenes permitidos para CORS ---
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://pmbok-app-prod.eba-p9tjqp8p.us-east-1.elasticbeanstalk.com",
]

CORS_ALLOW_HEADERS = [
    'content-type',
    'authorization',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# --- Configuración de la Base de Datos ---
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ['DB_NAME'],
        'USER': os.environ['DB_USER'],
        'PASSWORD': os.environ['DB_PASSWORD'],
        'HOST': os.environ['DB_HOST'],
        'PORT': os.environ.get('DB_PORT', '5432'),
        'OPTIONS': {'sslmode': os.environ.get('DB_SSLMODE', 'require')},

    }
}


# --- Validadores de Contraseña ---
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# --- Internacionalización ---
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# --- Archivos Estáticos ---
# STATIC_URL = 'static/'
# STATIC_ROOT = BASE_DIR.parent / 'static'
# STATIC_ROOT = os.environ.get('STATIC_ROOT', os.path.join(BASE_DIR, 'static'))
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'api.CustomUser'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "stream": "ext://sys.stdout",
        },
    },
    "loggers": {
        "django.security.DisallowedHost": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}

USE_X_FORWARDED_HOST = True
