# backend/api/management/commands/seed_pmbok.py
from django.core.management.base import BaseCommand
from api.models import ProcessState, PMBOKProcess

class Command(BaseCommand):
    help = 'Seeds the database with PMBOK processes, states, and ITTOs'

    def handle(self, *args, **options):
        self.stdout.write('Deleting existing data...')
        PMBOKProcess.objects.all().delete()
        ProcessState.objects.all().delete()

        self.stdout.write('Creating process states...')
        
        # Crear los 5 estados
        state1, _ = ProcessState.objects.get_or_create(
            name="Base Estratégica",
            defaults={'tailwind_bg_color': 'bg-indigo-800', 'tailwind_text_color': 'text-white'}
        )
        state2_biweekly, _ = ProcessState.objects.get_or_create(
            name="Ritmo de Sprint (2 Semanas)",
            defaults={'tailwind_bg_color': 'bg-blue-700', 'tailwind_text_color': 'text-white'}
        )
        state2_daily, _ = ProcessState.objects.get_or_create(
            name="Ritmo Diario",
            defaults={'tailwind_bg_color': 'bg-green-600', 'tailwind_text_color': 'text-white'}
        )
        state3, _ = ProcessState.objects.get_or_create(
            name="Burocracia Innecesaria",
            defaults={'tailwind_bg_color': 'bg-amber-500', 'tailwind_text_color': 'text-white'}
        )
        state4, _ = ProcessState.objects.get_or_create(
            name="Inaplicable",
            defaults={'tailwind_bg_color': 'bg-gray-400', 'tailwind_text_color': 'text-gray-800'}
        )
        
        # Diccionario de procesos con todos los detalles (ITTOs)
        # Los ítems están separados por '\n' para facilitar el split en el frontend.
        processes_data = {
            state1: [
                (1, "Desarrollar el Acta de Constitución del Proyecto", "Documentos de negocio\nAcuerdos\nFactores ambientales de la empresa\nActivos de los procesos de la organización", "Juicio de expertos\nRecopilación de datos\nHabilidades interpersonales y de equipo\nReuniones", "Acta de Constitución del Proyecto\nRegistro de supuestos"),
                (2, "Identificar a los Interesados", "Acta de Constitución del Proyecto\nDocumentos de negocio\nPlan para la dirección del proyecto\nDocumentos del proyecto\nAcuerdos", "Juicio de expertos\nRecopilación de datos\nAnálisis de datos\nRepresentación de datos\nReuniones", "Registro de interesados\nSolicitudes de cambio\nActualizaciones al plan para la dirección del proyecto"),
                (5, "Planificar la Gestión del Alcance", "Acta de Constitución del Proyecto\nPlan para la dirección del proyecto\nFactores ambientales de la empresa\nActivos de los procesos de la organización", "Juicio de expertos\nAnálisis de datos\nReuniones", "Plan de gestión del alcance\nPlan de gestión de los requisitos"),
                (6, "Recopilar Requisitos", "Acta de Constitución del Proyecto\nPlan para la dirección del proyecto\nDocumentos del proyecto\nDocumentos de negocio\nAcuerdos", "Juicio de expertos\nRecopilación de datos\nAnálisis de datos\nRepresentación de datos\nHabilidades interpersonales y de equipo\nDiagrama de contexto\nPrototipos", "Documentación de requisitos\nMatriz de trazabilidad de requisitos"),
                (7, "Definir el Alcance", "Acta de Constitución del Proyecto\nPlan para la dirección del proyecto\nDocumentos del proyecto\nFactores ambientales de la empresa\nActivos de los procesos de la organización", "Juicio de expertos\nAnálisis de datos\nToma de decisiones\nHabilidades interpersonales y de equipo\nAnálisis del producto", "Enunciado del alcance del proyecto\nActualizaciones a los documentos del proyecto"),
                (8, "Crear la EDT/WBS", "Plan para la dirección del proyecto\nDocumentos del proyecto\nFactores ambientales de la empresa\nActivos de los procesos de la organización", "Juicio de expertos\nDescomposición", "Línea base del alcance\nActualizaciones a los documentos del proyecto"),
                (9, "Planificar la Gestión del Cronograma", "Acta de Constitución del Proyecto\nPlan para la dirección del proyecto\nFactores ambientales de la empresa\nActivos de los procesos de la organización", "Juicio de expertos\nAnálisis de datos\nReuniones", "Plan de gestión del cronograma"),
                (12, "Planificar la Gestión de los Riesgos", "Acta de Constitución del Proyecto\nPlan para la dirección del proyecto\nDocumentos del proyecto\nFactores ambientales de la empresa\nActivos de los procesos de la organización", "Juicio de expertos\nAnálisis de datos\nReuniones", "Plan de gestión de los riesgos"),
                (13, "Identificar los Riesgos", "Plan para la dirección del proyecto\nDocumentos del proyecto\nAcuerdos\nDocumentación de las adquisiciones\nFactores ambientales de la empresa", "Juicio de expertos\nRecopilación de datos\nAnálisis de datos\nHabilidades interpersonales y de equipo\nListas rápidas\nReuniones", "Registro de riesgos\nInforme de riesgos\nActualizaciones a los documentos del proyecto"),
                (19, "Planificar la Gestión de los Costos", "Acta de Constitución del Proyecto\nPlan para la dirección del proyecto\nFactores ambientales de la empresa\nActivos de los procesos de la organización", "Juicio de expertos\nAnálisis de datos\nReuniones", "Plan de gestión de los costos"),
                (23, "Determinar el Presupuesto", "Plan para la dirección del proyecto\nDocumentos del proyecto\nDocumentos de negocio\nAcuerdos\nFactores ambientales de la empresa", "Juicio de expertos\nAgregación de costos\nAnálisis de datos\nRevisión de información histórica\nConciliación del límite de financiamiento\nFinanciamiento", "Línea base de costos\nRequisitos de financiamiento del proyecto\nActualizaciones a los documentos del proyecto"),
            ],
            state2_biweekly: [
                (28, "Gestionar el Conocimiento del Proyecto", "Plan para la dirección del proyecto\nDocumentos del proyecto\nEntregables\nFactores ambientales de la empresa\nActivos de los procesos de la organización", "Juicio de expertos\nGestión del conocimiento\nGestión de la información\nHabilidades interpersonales y de equipo", "Registro de lecciones aprendidas\nActualizaciones al plan para la dirección del proyecto\nActualizaciones a los activos de los procesos"),
                (29, "Gestionar el Involucramiento de los Interesados", "Plan para la dirección del proyecto\nDocumentos del proyecto\nFactores ambientales de la empresa\nActivos de los procesos de la organización", "Juicio de expertos\nHabilidades de comunicación\nHabilidades interpersonales y de equipo\nReglas básicas\nReuniones", "Solicitudes de cambio\nActualizaciones al plan para la dirección del proyecto\nActualizaciones a los documentos del proyecto"),
                (37, "Monitorear y Controlar el Trabajo del Proyecto", "Plan para la dirección del proyecto\nDocumentos del proyecto\nInformación de desempeño del trabajo\nAcuerdos\nFactores ambientales de la empresa", "Juicio de expertos\nAnálisis de datos\nToma de decisiones\nReuniones", "Informes de desempeño del trabajo\nSolicitudes de cambio\nActualizaciones al plan para la dirección del proyecto"),
                (38, "Realizar el Control Integrado de Cambios", "Plan para la dirección del proyecto\nDocumentos del proyecto\nInformes de desempeño del trabajo\nSolicitudes de cambio\nFactores ambientales de la empresa", "Juicio de expertos\nHerramientas de control de cambios\nAnálisis de datos\nToma de decisiones\nReuniones", "Solicitudes de cambio aprobadas\nActualizaciones al plan para la dirección del proyecto\nActualizaciones a los documentos del proyecto"),
                (43, "Monitorear los Riesgos", "Plan para la dirección del proyecto\nDocumentos del proyecto\nDatos de desempeño del trabajo\nInformes de desempeño del trabajo", "Análisis de datos\nAuditorías de riesgos\nReuniones", "Información de desempeño del trabajo\nSolicitudes de cambio\nActualizaciones al plan para la dirección del proyecto"),
                (45, "Controlar la Calidad", "Plan para la dirección del proyecto\nDocumentos del proyecto\nSolicitudes de cambio aprobadas\nEntregables\nDatos de desempeño del trabajo", "Recopilación de datos\nAnálisis de datos\nInspección\nPruebas/Evaluaciones de producto\nRepresentación de datos\nReuniones", "Mediciones de control de calidad\nEntregables verificados\nInformación de desempeño del trabajo"),
                (46, "Validar el Alcance", "Plan para la dirección del proyecto\nDocumentos del proyecto\nEntregables verificados\nDatos de desempeño del trabajo", "Inspección\nToma de decisiones", "Entregables aceptados\nInformación de desempeño del trabajo\nSolicitudes de cambio"),
            ],
            state2_daily: [
                (27, "Dirigir y Gestionar el Trabajo del Proyecto", "Plan para la dirección del proyecto\nDocumentos del proyecto\nSolicitudes de cambio aprobadas\nFactores ambientales de la empresa\nActivos de los procesos de la organización", "Juicio de expertos\nSistema de información para la dirección de proyectos\nReuniones", "Entregables\nDatos de desempeño del trabajo\nRegistro de incidentes\nSolicitudes de cambio"),
                (32, "Dirigir al Equipo", "Plan para la dirección del proyecto\nDocumentos del proyecto\nInformes de desempeño del trabajo\nEvaluaciones del desempeño del equipo\nFactores ambientales de la empresa", "Habilidades interpersonales y de equipo\nSistema de información para la dirección de proyectos", "Solicitudes de cambio\nActualizaciones al plan para la dirección del proyecto\nActualizaciones a los documentos del proyecto"),
            ],
            state3: [
                 (3, "Desarrollar el Plan para la Dirección del Proyecto", "Acta de Constitución del Proyecto\nSalidas de otros procesos\nFactores ambientales de la empresa\nActivos de los procesos de la organización", "Juicio de expertos\nRecopilación de datos\nHabilidades interpersonales y de equipo\nReuniones", "Plan para la dirección del proyecto"),
                 (4, "Planificar el Involucramiento de los Interesados", "Acta de Constitución del Proyecto\nPlan para la dirección del proyecto\nDocumentos del proyecto\nAcuerdos\nFactores ambientales de la empresa", "Juicio de expertos\nRecopilación de datos\nToma de decisiones\nRepresentación de datos\nReuniones", "Plan de involucramiento de los interesados"),
                 (10, "Definir las Actividades", "Plan para la dirección del proyecto\nFactores ambientales de la empresa\nActivos de los procesos de la organización", "Juicio de expertos\nDescomposición\nPlanificación gradual\nReuniones", "Lista de actividades\nAtributos de la actividad\nLista de hitos\nSolicitudes de cambio"),
                 (11, "Secuenciar las Actividades", "Plan para la dirección del proyecto\nDocumentos del proyecto\nFactores ambientales de la empresa\nActivos de los procesos de la organización", "Método de diagramación por precedencia (PDM)\nDeterminación e integración de las dependencias\nAdelantos y retrasos\nSistema de información para la dirección de proyectos", "Diagramas de red del cronograma del proyecto\nActualizaciones a los documentos del proyecto"),
                 (14, "Realizar el Análisis Cualitativo de Riesgos", "Plan para la dirección del proyecto\nDocumentos del proyecto\nFactores ambientales de la empresa\nActivos de los procesos de la organización", "Juicio de expertos\nRecopilación de datos\nAnálisis de datos\nHabilidades interpersonales y de equipo\nCategorización de riesgos\nRepresentación de datos\nReuniones", "Actualizaciones a los documentos del proyecto"),
                 (16, "Planificar la Respuesta a los Riesgos", "Plan para la dirección del proyecto\nDocumentos del proyecto\nFactores ambientales de la empresa\nActivos de los procesos de la organización", "Juicio de expertos\nRecopilación de datos\nHabilidades interpersonales y de equipo\nEstrategias para amenazas y oportunidades\nEstrategias para el riesgo general del proyecto\nAnálisis de datos\nToma de decisiones", "Solicitudes de cambio\nActualizaciones al plan para la dirección del proyecto"),
                 (21, "Estimar la Duración de las Actividades", "Plan para la dirección del proyecto\nDocumentos del proyecto\nFactores ambientales de la empresa\nActivos de los procesos de la organización", "Juicio de expertos\nEstimación análoga\nEstimación paramétrica\nEstimación por tres valores\nEstimación ascendente\nAnálisis de datos\nToma de decisiones\nReuniones", "Estimaciones de la duración\nBase de las estimaciones\nActualizaciones a los documentos del proyecto"),
                 (22, "Desarrollar el Cronograma", "Plan para la dirección del proyecto\nDocumentos del proyecto\nAcuerdos\nFactores ambientales de la empresa\nActivos de los procesos de la organización", "Análisis de la red del cronograma\nMétodo de la ruta crítica\nOptimización de recursos\nAnálisis de datos\nAdelantos y retrasos\nCompresión del cronograma\nPlanificación ágil de liberaciones", "Línea base del cronograma\nCronograma del proyecto\nDatos del cronograma\nCalendarios del proyecto"),
                 (24, "Planificar la Gestión de la Calidad", "Acta de Constitución del Proyecto\nPlan para la dirección del proyecto\nDocumentos del proyecto\nFactores ambientales de la empresa\nActivos de los procesos de la organización", "Juicio de expertos\nRecopilación de datos\nAnálisis de datos\nToma de decisiones\nRepresentación de datos\nPlanificación de pruebas e inspección\nReuniones", "Plan de gestión de la calidad\nMétricas de calidad\nActualizaciones al plan para la dirección del proyecto"),
                 (25, "Planificar la Gestión de las Comunicaciones", "Acta de Constitución del Proyecto\nPlan para la dirección del proyecto\nDocumentos del proyecto\nFactores ambientales de la empresa\nActivos de los procesos de la organización", "Juicio de expertos\nAnálisis de requisitos de comunicación\nTecnología de la comunicación\nModelos de comunicación\nMétodos de comunicación\nHabilidades interpersonales y de equipo", "Plan de gestión de las comunicaciones\nActualizaciones al plan para la dirección del proyecto"),
                 (31, "Desarrollar el Equipo", "Plan para la dirección del proyecto\nDocumentos del proyecto\nFactores ambientales de la empresa\nActivos de los procesos de la organización", "Coubicación (Colocation)\nEquipos virtuales\nTecnología de la comunicación\nHabilidades interpersonales y de equipo\nReconocimiento y recompensas\nCapacitación\nEvaluaciones individuales y de equipo\nReuniones", "Evaluaciones del desempeño del equipo\nSolicitudes de cambio\nActualizaciones al plan para la dirección del proyecto"),
                 (36, "Implementar la Respuesta a los Riesgos", "Plan para la dirección del proyecto\nDocumentos del proyecto\nActivos de los procesos de la organización", "Juicio de expertos\nHabilidades interpersonales y de equipo\nSistema de información para la dirección de proyectos", "Solicitudes de cambio\nActualizaciones a los documentos del proyecto"),
            ],
            state4: [
                (15, "Realizar el Análisis Cuantitativo de Riesgos", "Plan para la dirección del proyecto\nDocumentos del proyecto\nFactores ambientales de la empresa\nActivos de los procesos de la organización", "Juicio de expertos\nRecopilación de datos\nHabilidades interpersonales y de equipo\nRepresentaciones de la incertidumbre\nAnálisis de datos", "Actualizaciones a los documentos del proyecto"),
                (17, "Planificar la Gestión de Recursos", "Acta de Constitución del Proyecto\nPlan para la dirección del proyecto\nDocumentos del proyecto\nFactores ambientales de la empresa\nActivos de los procesos de la organización", "Juicio de expertos\nRepresentación de datos\nTeoría de la organización\nReuniones", "Plan de gestión de los recursos\nActa de constitución del equipo\nActualizaciones a los documentos del proyecto"),
                (18, "Estimar los Recursos de las Actividades", "Plan para la dirección del proyecto\nDocumentos del proyecto\nFactores ambientales de la empresa\nActivos de los procesos de la organización", "Juicio de expertos\nEstimación ascendente\nEstimación análoga\nEstimación paramétrica\nAnálisis de datos\nSistema de información para la dirección de proyectos\nReuniones", "Requisitos de recursos\nBase de las estimaciones\nEstructura de desglose de recursos"),
                (20, "Estimar los Costos", "Plan para la dirección del proyecto\nDocumentos del proyecto\nFactores ambientales de la empresa\nActivos de los procesos de la organización", "Juicio de expertos\nEstimación análoga\nEstimación paramétrica\nEstimación ascendente\nEstimación por tres valores\nAnálisis de datos\nToma de decisiones", "Estimaciones de costos\nBase de las estimaciones\nActualizaciones a los documentos del proyecto"),
                (26, "Planificar la Gestión de las Adquisiciones", "Documentos de negocio\nPlan para la dirección del proyecto\nDocumentos del proyecto\nFactores ambientales de la empresa\nActivos de los procesos de la organización", "Juicio de expertos\nRecopilación de datos\nAnálisis de datos\nAnálisis de hacer o comprar\nCriterios de selección de proveedores\nReuniones", "Plan de gestión de las adquisiciones\nEstrategia de la adquisición\nDocumentos de la licitación"),
                (30, "Adquirir Recursos", "Plan para la dirección del proyecto\nDocumentos del proyecto\nFactores ambientales de la empresa\nActivos de los procesos de la organización", "Toma de decisiones\nHabilidades interpersonales y de equipo\nAsignación previa\nEquipos virtuales", "Asignaciones de recursos físicos\nAsignaciones del equipo del proyecto\nCalendarios de recursos\nSolicitudes de cambio"),
                (34, "Efectuar las Adquisiciones", "Plan para la dirección del proyecto\nDocumentos del proyecto\nDocumentación de las adquisiciones\nPropuestas de los vendedores\nFactores ambientales de la empresa", "Juicio de expertos\nPublicidad\nConferencias de oferentes\nAnálisis de datos\nHabilidades interpersonales y de equipo", "Vendedores seleccionados\nAcuerdos\nSolicitudes de cambio\nActualizaciones al plan para la dirección del proyecto"),
                (40, "Controlar el Cronograma", "Plan para la dirección del proyecto\nDocumentos del proyecto\nDatos de desempeño del trabajo\nActivos de los procesos de la organización", "Análisis de datos\nMétodo de la ruta crítica\nSistema de información para la dirección de proyectos\nOptimización de recursos\nAdelantos y retrasos\nCompresión del cronograma", "Información de desempeño del trabajo\nPronósticos del cronograma\nSolicitudes de cambio"),
                (41, "Controlar los Costos", "Plan para la dirección del proyecto\nDocumentos del proyecto\nRequisitos de financiamiento del proyecto\nDatos de desempeño del trabajo\nActivos de los procesos de la organización", "Juicio de expertos\nAnálisis de datos\nÍndice de Desempeño del Trabajo por Completar (TCPI)\nSistema de información para la dirección de proyectos", "Información de desempeño del trabajo\nPronósticos de costos\nSolicitudes de cambio"),
                (42, "Monitorear las Comunicaciones", "Plan para la dirección del proyecto\nDocumentos del proyecto\nDatos de desempeño del trabajo\nFactores ambientales de la empresa\nActivos de los procesos de la organización", "Juicio de expertos\nSistema de información para la dirección de proyectos (PMIS)\nRepresentación de datos\nHabilidades interpersonales y de equipo\nReuniones", "Información de desempeño del trabajo\nSolicitudes de cambio\nActualizaciones al plan para la dirección del proyecto"),
                (44, "Controlar los Recursos", "Plan para la dirección del proyecto\nDocumentos del proyecto\nDatos de desempeño del trabajo\nAcuerdos\nActivos de los procesos de la organización", "Análisis de datos\nResolución de problemas\nHabilidades interpersonales y de equipo\nSistema de información para la dirección de proyectos (PMIS)", "Información de desempeño del trabajo\nSolicitudes de cambio\nActualizaciones al plan para la dirección del proyecto"),
                (47, "Controlar el Alcance", "Plan para la dirección del proyecto\nDocumentos del proyecto\nDatos de desempeño del trabajo\nActivos de los procesos de la organización", "Análisis de datos\nAnálisis de variación", "Información de desempeño del trabajo\nSolicitudes de cambio\nActualizaciones al plan para la dirección del proyecto"),
                (48, "Controlar las Adquisiciones", "Plan para la dirección del proyecto\nDocumentos del proyecto\nAcuerdos\nDocumentación de las adquisiciones\nSolicitudes de cambio aprobadas\nDatos de desempeño del trabajo", "Juicio de expertos\nAdministración de reclamaciones\nAnálisis de datos\nInspección\nAuditorías", "Adquisiciones cerradas\nInformación de desempeño del trabajo\nSolicitudes de cambio"),
                (49, "Cerrar el Proyecto o Fase", "Acta de Constitución del Proyecto\nPlan para la dirección del proyecto\nDocumentos del proyecto\nEntregables aceptados\nDocumentos de negocio\nAcuerdos", "Juicio de expertos\nRecopilación de datos\nAnálisis de datos\nReuniones", "Transferencia del producto, servicio o resultado final\nInforme final\nActualizaciones a los activos de los procesos"),
            ]
        }

        self.stdout.write('Seeding PMBOK processes with ITTOs...')
        for state, process_list in processes_data.items():
            for num, name, inputs, tools, outputs in process_list:
                PMBOKProcess.objects.create(
                    process_number=num,
                    name=name,
                    state=state,
                    inputs=inputs,
                    tools_and_techniques=tools,
                    outputs=outputs
                )
        
        self.stdout.write(self.style.SUCCESS('Database has been seeded successfully with all details!'))