# /webapps/erd-ecosystem/apps/pmbok/.github/tag-final-on-main.yaml
name: Tag Final on Main

on:
  push:
    branches:
      - main

# FASE 2 (NUEVO): Evitar carreras/reintentos creando tags duplicados
# - Concurrency evita ejecuciones simultáneas en la misma rama.
# - Además, hacemos idempotencia por commit: si el SHA ya tiene vX.Y.Z, no recreamos.
concurrency:
  group: tag-final-on-main-${{ github.ref }}
  cancel-in-progress: false

jobs:
  tag-final:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # FASE 2 (NUEVO): asegurar tags disponibles
          fetch-tags: true

      # FASE 2 (NUEVO): asegurar tags frescos (checkout a veces no trae todo en forks/edge cases)
      - name: Fetch tags (force)
        run: |
          set -euo pipefail
          git fetch --tags --force

      # FASE 2 (NUEVO): idempotencia por commit
      - name: Skip if current commit already has the final tag for this version
        id: final_guard
        run: |
          set -euo pipefail
          VERSION="$(cat VERSION | tr -d '[:space:]')"
          TAG_NAME="v$VERSION"
          echo "Version: $VERSION"
          echo "Tag: $TAG_NAME"

          SHA="$(git rev-parse HEAD)"
          echo "Current SHA: $SHA"

          # Si este SHA ya tiene el tag final exacto, no hacemos nada
          EXISTING_ON_SHA="$(git tag --points-at "$SHA" | grep -Fx "$TAG_NAME" || true)"

          if [ -n "$EXISTING_ON_SHA" ]; then
            echo "✅ This commit already has final tag: $TAG_NAME"
            echo "skip=true" >> "$GITHUB_OUTPUT"
          else
            echo "skip=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Create Final Tag
        if: ${{ steps.final_guard.outputs.skip != 'true' }}
        run: |
          set -euo pipefail
          VERSION="$(cat VERSION | tr -d '[:space:]')"
          TAG_NAME="v$VERSION"
          
          if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
            echo "Tag $TAG_NAME already exists. Skipping."
          else
            echo "Creating tag $TAG_NAME"
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git tag -a "$TAG_NAME" -m "Release $TAG_NAME"
            git push origin "$TAG_NAME"
          fi
