# /webapps/erd-ecosystem/apps/pmbok/.github/tag-rc-on-staging.yaml

name: Tag RC on Staging

on:
  push:
    branches:
      - staging

# FASE 2 (NUEVO): Evitar carreras/reintentos creando RCs extra
# - Concurrency evita ejecuciones simultáneas en la misma rama.
# - Además, hacemos el workflow idempotente por commit: si el SHA ya tiene un vX.Y.Z-rc*,
#   no creamos otro.
concurrency:
  group: tag-rc-on-staging-${{ github.ref }}
  cancel-in-progress: false

jobs:
  tag-rc:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # FASE 2 (NUEVO): asegurar tags disponibles para calcular RC correctamente
          fetch-tags: true

      # FASE 2 (NUEVO): asegurar tags frescos (checkout a veces no trae todo en forks/edge cases)
      - name: Fetch tags (force)
        run: |
          set -euo pipefail
          git fetch --tags --force

      # FASE 2 (NUEVO): idempotencia por commit
      - name: Skip if current commit already has an RC tag for this version
        id: rc_guard
        run: |
          set -euo pipefail
          VERSION="$(cat VERSION | tr -d '[:space:]')"
          echo "Base version: $VERSION"

          SHA="$(git rev-parse HEAD)"
          echo "Current SHA: $SHA"

          # Si este SHA ya tiene un tag RC de esta versión, no creamos otro
          EXISTING_ON_SHA="$(git tag --points-at "$SHA" | grep -E "^v${VERSION}-rc[0-9]+$" || true)"

          if [ -n "$EXISTING_ON_SHA" ]; then
            echo "✅ This commit already has RC tag(s):"
            echo "$EXISTING_ON_SHA"
            echo "skip=true" >> "$GITHUB_OUTPUT"
          else
            echo "skip=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Calculate Next RC Tag
        id: tag_calc
        if: ${{ steps.rc_guard.outputs.skip != 'true' }}
        run: |
          set -euo pipefail
          VERSION="$(cat VERSION | tr -d '[:space:]')"
          echo "Base version: $VERSION"
          
          # Buscar tags existentes para esta versión (vX.Y.Z-rc*)
          EXISTING_RCS="$(git tag -l "v$VERSION-rc*" | sort -V | tail -n 1)"
          
          if [ -z "$EXISTING_RCS" ]; then
            NEW_TAG="v$VERSION-rc1"
          else
            # Extraer el número del último rc y sumar 1
            LAST_NUM="$(echo "$EXISTING_RCS" | sed -E "s/v$VERSION-rc([0-9]+)/\1/")"
            NEXT_NUM=$((LAST_NUM + 1))
            NEW_TAG="v$VERSION-rc$NEXT_NUM"
          fi
          
          echo "New tag: $NEW_TAG"
          echo "new_tag=$NEW_TAG" >> "$GITHUB_OUTPUT"

      - name: Push RC Tag
        if: ${{ steps.rc_guard.outputs.skip != 'true' }}
        run: |
          set -euo pipefail
          TAG="${{ steps.tag_calc.outputs.new_tag }}"

          # FASE 2 (NUEVO): si por algún motivo el tag ya existe, no hacemos nada
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists. Skipping."
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "$TAG" -m "Release Candidate $TAG"
          git push origin "$TAG"

