# /webapps/erd-ecosystem/apps/pmbok/frontend/Taskfile.yaml
version: "3"

tasks:
  install:
    desc: "📦 Instalar dependencias (Local)"
    cmds:
      - npm install

  install-ci:
    desc: "📦 Instalar dependencias (CI - Clean)"
    # npm ci borra node_modules y instala exactamente lo que dice el package-lock.json
    cmds:
      - npm ci

  # ✅ NEW: Tarea de Linting separada
  lint:
    desc: "🧹 Validar estilo (ESLint)"
    cmds:
      - echo "🧹 [FRONTEND] Linting..."
      - npm run lint

  # ✅ NEW: Tarea de Build separada
  build:
    desc: "🧱 Validar compilación (Build)"
    cmds:
      - echo "🧱 [FRONTEND] Building..."
      - npm run build

  test:
    desc: "🧪 Ejecutar validaciones (Lint + Build)"
    cmds:
      # Como no hay tests unitarios aún, validamos calidad de código y compilación
      - task: lint
      - task: build

  run:
    desc: "🚀 Ejecutar servidor de desarrollo (Vite)"
    cmds:
      - npm run dev