version: '3'

tasks:
  # 1. Tarea para probar solo el Backend
  test:backend:
    desc: Run backend tests only
    dir: backend  # <-- ¡La magia! Entra a la carpeta backend automáticamente
    cmds:
      - task test

  # 2. Tarea para probar solo el Frontend
  test:frontend:
    desc: Run frontend tests (lint + build) only
    dir: frontend # <-- Entra a la carpeta frontend automáticamente
    cmds:
      - task test

  # 3. Tarea Maestra: ¡Prueba TODO!
  test:
    desc: Run ALL tests (Backend + Frontend)
    cmds:
      - echo "🚀 Iniciando pruebas del BACKEND..."
      - task: test:backend
      
      - echo "-----------------------------------"
      - echo "🚀 Iniciando pruebas del FRONTEND..."
      - task: test:frontend
      
      - echo "✅ ¡Todas las pruebas finalizaron con éxito!"