# /webapps/erd-ecosystem/apps/pmbok/backend/Taskfile.yaml
version: '3'

# Variables de entorno por defecto para que Django arranque sin errores
env:
  # Forzamos modo DEBUG para evitar validaciones estrictas de seguridad en local
  DJANGO_DEBUG: "True"
  # Definimos una SECRET_KEY cualquiera para que settings.py no falle al arrancar
  SECRET_KEY: "insecure-test-key-for-task-runner"
  # Valores placeholder para la DB.
  # Aunque usemos SimpleTestCase, Django lee settings.py al inicio y necesita estos valores.
  # ✅ FIX: Alineado con docker-compose para que pueda conectar a la DB local
  DB_NAME: "pmbok_db"
  DB_USER: "pmbok_user"
  DB_PASSWORD: "secretpassword123"
  DB_HOST: "localhost"
  DB_PORT: "5432"

tasks:
  install:
    desc: "📦 Instalar dependencias (Local)"
    cmds:
      - poetry install --no-root

  install-ci:
    desc: "📦 Instalar dependencias (CI - Strict)"
    cmds:
      # --sync asegura que el entorno quede idéntico al lockfile (borra extra packages)
      - poetry install --no-root --sync

  test:
    desc: "🧪 Ejecutar pruebas unitarias (Pytest)"
    # Ejecuta los tests usando la configuración de pytest.ini
    cmds:
      - echo "🧪 [BACKEND] Ejecutando tests..."
      - poetry run pytest

  # ✅ NEW: Estandarización de Linting
  lint:
    desc: "🧹 Check de código (Flake8/Black)"
    cmds:
      - echo "🧹 [BACKEND] Linting..."
      # Descomentar cuando configures linters:
      # - poetry run flake8 .
      # - poetry run black --check .

  # ✅ NEW: Estandarización de Formateo
  fmt:
    desc: "🎨 Formatear código (Auto-fix)"
    cmds:
      - echo "🎨 [BACKEND] Formatting..."
      # - poetry run black .

  run:
    desc: "🚀 Ejecutar servidor de desarrollo (Directo)"
    cmds:
      - poetry run python manage.py runserver 0.0.0.0:8000