# /webapps/erd-ecosystem/apps/pmbok/backend/Taskfile.yaml
version: '3'

# Variables de entorno por defecto para que Django arranque sin errores
env:
  # Forzamos modo DEBUG para evitar validaciones estrictas de seguridad en local
  DJANGO_DEBUG: "True"
  # Definimos una SECRET_KEY cualquiera para que settings.py no falle al arrancar
  SECRET_KEY: "insecure-test-key-for-task-runner"
  # Valores placeholder para la DB.
  # Aunque usemos SimpleTestCase, Django lee settings.py al inicio y necesita estos valores.
  DB_NAME: "pmbok_test_db"
  DB_USER: "testuser"
  DB_PASSWORD: "testpassword"
  DB_HOST: "localhost"
  DB_PORT: "5432"

tasks:
  install:
    desc: Install dependencies (Local Dev)
    cmds:
      - poetry install --no-root

  install-ci:
    desc: install/download package dependencies (CI mode)
    cmds:
      - poetry install --no-root

  test:
    desc: run tests
    # Ejecuta los tests usando la configuración de pytest.ini
    cmds:
      - poetry run pytest

  run:
    desc: Run dev server (Django)
    cmds:
      - poetry run python manage.py runserver 0.0.0.0:8000