# /webapps/erd-ecosystem/apps/pmbok/backend/Taskfile.yaml
version: "3"

# Definimos variables de entorno por defecto solo para este Taskfile
env:
  # Forzamos modo DEBUG para que IS_PROD sea False y evitar el check estricto de SECRET_KEY
  DJANGO_DEBUG: "true"
  # Definimos una SECRET_KEY cualquiera para que no falle al arrancar
  SECRET_KEY: "insecure-test-key-for-ci-only"
  # Variables de base de datos dummy.
  # NOTA: Si tus tests requieren DB real, pytest-django intentará crear una DB de prueba.
  # Si usas SQLite para tests (recomendado para CI rápido), esto puede variar.
  # Por ahora ponemos valores placeholder para que settings.py no explote al leer os.environ
  DB_NAME: "pmbok_test_db"
  DB_USER: "testuser"
  DB_PASSWORD: "testpassword"
  DB_HOST: "localhost"
  DB_PORT: "5432"

tasks:
  install:
    desc: Install dependencies
    cmds:
      - poetry install --no-root

  install-ci:
    desc: install/download package dependencies (CI mode)
    cmds:
      - poetry install --no-root

  test:
    desc: run tests
    # pytest-django usará una base de datos en memoria o creará una de prueba si está configurado
    # Si tus tests no necesitan DB real, usa --nomigrations para ir más rápido
    cmds:
      - poetry run pytest

  run:
    desc: Run dev server
    cmds:
      - poetry run python manage.py runserver 0.0.0.0:8000